// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Xml;
using Sample.Models;

namespace Sample
{
    public partial class MockInputModel
    {
        internal virtual void XmlModelWriteCore(XmlWriter writer, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<MockInputModel>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "X"))
            {
                throw new FormatException($"The model {nameof(MockInputModel)} does not support writing '{format}' format.");
            }

            if (Optional.IsDefined(Prop1))
            {
                this.SerializationMethod(writer, options);
            }
            if (Optional.IsDefined(Prop2))
            {
                this.SerializationMethod(writer, options);
            }
        }
    }
}
