// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Xml.Linq;
using Sample.Models;

namespace Sample
{
    public partial class MockInputModel
    {
        internal static MockInputModel DeserializeMockInputModel(XElement element, ModelReaderWriterOptions options)
        {
            if ((element == null))
            {
                return null;
            }

            string id = default;
            string name = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();

            foreach (var attr in element.Attributes())
            {
                string localName = attr.Name.LocalName;
                if ((localName == "id"))
                {
                    DeserializationMethod(attr, ref id);
                    continue;
                }
            }

            foreach (var child in element.Elements())
            {
                string localName = child.Name.LocalName;
                if ((localName == "name"))
                {
                    name = ((string)child);
                    continue;
                }
            }
            return new MockInputModel(id, name, additionalBinaryDataProperties);
        }
    }
}
