// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Xml;
using System.Xml.Linq;
using Sample.Models;

namespace Sample
{
    public partial class Model
    {
        internal virtual void XmlModelWriteCore(XmlWriter writer, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<Model>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "X"))
            {
                throw new FormatException($"The model {nameof(Model)} does not support writing '{format}' format.");
            }

            if (Optional.IsDefined(Prop2))
            {
                writer.WriteStartElement("prop1");
                writer.WriteValue(Prop2);
                writer.WriteEndElement();
            }
        }

        internal static Model DeserializeModel(XElement element, ModelReaderWriterOptions options)
        {
            if ((element == null))
            {
                return null;
            }

            string prop2 = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();

            foreach (var child in element.Elements())
            {
                string localName = child.Name.LocalName;
                if ((localName == "prop1"))
                {
                    prop2 = ((string)child);
                    continue;
                }
            }
            return new Model(prop2, additionalBinaryDataProperties);
        }
    }
}
