// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.IO;
using System.Xml;
using System.Xml.Linq;
using Sample;

namespace Sample.Models
{
    public partial class MockInputModel : IPersistableModel<MockInputModel>
    {
        protected virtual MockInputModel PersistableModelCreateCore(BinaryData data, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<MockInputModel>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "X":
                    using (Stream dataStream = data.ToStream())
                    {
                        return MockInputModel.DeserializeMockInputModel(XElement.Load(dataStream, LoadOptions.PreserveWhitespace), options);
                    }
                default:
                    throw new FormatException($"The model {nameof(MockInputModel)} does not support reading '{options.Format}' format.");
            }
        }

        protected virtual BinaryData PersistableModelWriteCore(ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<MockInputModel>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "X":
                    using (MemoryStream stream = new MemoryStream(256))
                    {
                        using (XmlWriter writer = XmlWriter.Create(stream, ModelSerializationExtensions.XmlWriterSettings))
                        {
                            this.WriteXml(writer, options, "MockInputModel");
                        }
                        if ((stream.Position > int.MaxValue))
                        {
                            return BinaryData.FromStream(stream);
                        }
                        else
                        {
                            return new BinaryData(stream.GetBuffer().AsMemory(0, ((int)stream.Position)));
                        }
                    }
                default:
                    throw new FormatException($"The model {nameof(MockInputModel)} does not support writing '{options.Format}' format.");
            }
        }

        BinaryData IPersistableModel<MockInputModel>.Write(ModelReaderWriterOptions options) => this.PersistableModelWriteCore(options);

        MockInputModel IPersistableModel<MockInputModel>.Create(BinaryData data, ModelReaderWriterOptions options) => this.PersistableModelCreateCore(data, options);

        string IPersistableModel<MockInputModel>.GetFormatFromOptions(ModelReaderWriterOptions options) => "X";

        private void WriteXml(XmlWriter writer, ModelReaderWriterOptions options, string nameHint)
        {
            if ((nameHint != null))
            {
                writer.WriteStartElement(nameHint);
            }

            this.XmlModelWriteCore(writer, options);

            if ((nameHint != null))
            {
                writer.WriteEndElement();
            }
        }

        internal virtual void XmlModelWriteCore(XmlWriter writer, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<MockInputModel>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "X"))
            {
                throw new FormatException($"The model {nameof(MockInputModel)} does not support writing '{format}' format.");
            }

            if (Optional.IsDefined(Prop1))
            {
                writer.WriteStartElement("prop1");
                writer.WriteValue(Prop1);
                writer.WriteEndElement();
            }
            if (Optional.IsDefined(Prop2))
            {
                writer.WriteStartElement("prop2");
                writer.WriteValue(Prop2);
                writer.WriteEndElement();
            }
        }
    }
}
