// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using Sample.Models;

namespace Sample
{
#pragma warning disable TEST001 // CustomizedExperimentalModel is experimental and may change in future versions.
    [ModelReaderWriterBuildableAttribute(typeof(CustomizedExperimentalModel))]
#pragma warning restore TEST001 // CustomizedExperimentalModel is experimental and may change in future versions.
    [ModelReaderWriterBuildableAttribute(typeof(RegularModel))]
    public partial class SampleContext : ModelReaderWriterContext
    {
    }
}
