// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using Sample.Models;

namespace Sample
{
#pragma warning disable TEST001 // ExperimentalModel is experimental and may change in future versions.
    [ModelReaderWriterBuildableAttribute(typeof(ExperimentalModel))]
#pragma warning restore TEST001 // ExperimentalModel is experimental and may change in future versions.
    [ModelReaderWriterBuildableAttribute(typeof(RegularModel))]
    public partial class SampleContext : ModelReaderWriterContext
    {
    }
}
