// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using Sample.Models;

namespace Sample
{
#pragma warning disable TEST001 // global::Sample.Models.ExperimentalModel is experimental and may change in future versions.
    [ModelReaderWriterBuildableAttribute(typeof(global::Sample.Models.ExperimentalModel))]
#pragma warning restore TEST001 // global::Sample.Models.ExperimentalModel is experimental and may change in future versions.
    [ModelReaderWriterBuildableAttribute(typeof(global::Sample.Models.RegularModel))]
    public partial class SampleContext : ModelReaderWriterContext
    {
    }
}
