// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using Microsoft.TypeSpec.Generator.ClientModel.Tests.Providers.Definitions;
using Sample.Models;

namespace Sample
{
#pragma warning disable TEST001 // ModelReaderWriterContextDefinitionTests.ExperimentalDependencyModel is experimental and may change in future versions.
    [ModelReaderWriterBuildableAttribute(typeof(ModelReaderWriterContextDefinitionTests.ExperimentalDependencyModel))]
#pragma warning restore TEST001 // ModelReaderWriterContextDefinitionTests.ExperimentalDependencyModel is experimental and may change in future versions.
    [ModelReaderWriterBuildableAttribute(typeof(ParentModel))]
    public partial class SampleContext : ModelReaderWriterContext
    {
    }
}
