// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using Sample.Models;

namespace Sample
{
    [ModelReaderWriterBuildableAttribute(typeof(CustomizedModel))]
    [ModelReaderWriterBuildableAttribute(typeof(RegularModel))]
    public partial class SampleContext : ModelReaderWriterContext
    {
    }
}
