// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using Sample.Models;

namespace Sample
{
    [ModelReaderWriterBuildableAttribute(typeof(global::Sample.Models.CustomizedModel))]
    [ModelReaderWriterBuildableAttribute(typeof(global::Sample.Models.RegularModel))]
    public partial class SampleContext : ModelReaderWriterContext
    {
    }
}
