// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using Sample.Models;

namespace Sample
{
#pragma warning disable CS0618 // CustomizedObsoleteModel is obsolete and may be removed in future versions.
    [ModelReaderWriterBuildableAttribute(typeof(CustomizedObsoleteModel))]
#pragma warning restore CS0618 // CustomizedObsoleteModel is obsolete and may be removed in future versions.
    [ModelReaderWriterBuildableAttribute(typeof(RegularModel))]
    public partial class SampleContext : ModelReaderWriterContext
    {
    }
}
