// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using Microsoft.TypeSpec.Generator.ClientModel.Tests.Providers.Definitions;
using Sample.Models;

namespace Sample
{
#pragma warning disable CS0618 // global::Microsoft.TypeSpec.Generator.ClientModel.Tests.Providers.Definitions.ModelReaderWriterContextDefinitionTests.ObsoleteFrameworkType is obsolete and may be removed in future versions.
    [ModelReaderWriterBuildableAttribute(typeof(global::Microsoft.TypeSpec.Generator.ClientModel.Tests.Providers.Definitions.ModelReaderWriterContextDefinitionTests.ObsoleteFrameworkType))]
#pragma warning restore CS0618 // global::Microsoft.TypeSpec.Generator.ClientModel.Tests.Providers.Definitions.ModelReaderWriterContextDefinitionTests.ObsoleteFrameworkType is obsolete and may be removed in future versions.
    [ModelReaderWriterBuildableAttribute(typeof(global::Sample.Models.ParentModel))]
    public partial class SampleContext : ModelReaderWriterContext
    {
    }
}
