// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using Sample;

namespace Sample.Models
{
    public partial class DynamicModel
    {
        [ExperimentalAttribute("SCME0001")]
        private JsonPatch _patch;

        public DynamicModel(string p1)
        {
            Argument.AssertNotNull(p1, nameof(p1));

            P1 = p1;
        }

#pragma warning disable SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
        internal DynamicModel(string p1, in JsonPatch patch)
        {
            P1 = p1;
            _patch = patch;
        }
#pragma warning restore SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.

        [JsonIgnoreAttribute]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [ExperimentalAttribute("SCME0001")]
        public ref JsonPatch Patch => ref _patch;

        public string P1 { get; set; }
    }
}
