// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using Sample;

namespace Sample.Models
{
    public partial class DynamicModel
    {
        [ExperimentalAttribute("SCME0001")]
        private JsonPatch _patch;
        private IDictionary<string, string> _additionalStringProperties;
        private IDictionary<string, double> _additionalDoubleProperties;

        public DynamicModel(string p1)
        {
            Argument.AssertNotNull(p1, nameof(p1));

            P1 = p1;
            _additionalStringProperties = new ChangeTrackingDictionary<string, string>();
            _additionalDoubleProperties = new ChangeTrackingDictionary<string, double>();
        }

#pragma warning disable SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
        internal DynamicModel(string p1, IDictionary<string, string> additionalProperties, IDictionary<string, double> additionalDoubleProperties, in JsonPatch patch)
        {
            P1 = p1;
            _additionalStringProperties = additionalProperties;
            _additionalDoubleProperties = additionalDoubleProperties;
            _patch = patch;
        }
#pragma warning restore SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.

        [JsonIgnoreAttribute]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [ExperimentalAttribute("SCME0001")]
        public ref JsonPatch Patch => ref _patch;

        public string P1 { get; set; }

        public IDictionary<string, string> AdditionalProperties => _additionalStringProperties;

        public IDictionary<string, double> AdditionalDoubleProperties => _additionalDoubleProperties;
    }
}
