// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace Sample.Models
{
    internal readonly partial struct Cat
    {
        [ExperimentalAttribute("SCME0001")]
        private readonly JsonPatch _patch;

        public Cat(bool meows)
        {
            Meows = meows;
        }

#pragma warning disable SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
        internal Cat(bool meows, in JsonPatch patch)
        {
            Meows = meows;
            _patch = patch;
        }
#pragma warning restore SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.

        [JsonIgnoreAttribute]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [ExperimentalAttribute("SCME0001")]
        public JsonPatch Patch => _patch;

        public bool Meows { get; }
    }
}
