// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using Sample;

namespace Sample.Models
{
    public partial class DynamicModel
    {
        [ExperimentalAttribute("SCME0001")]
        private JsonPatch _patch;
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        public DynamicModel(string p1)
        {
            Argument.AssertNotNull(p1, nameof(p1));

            P1 = p1;
            _additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();
        }

#pragma warning disable SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
        internal DynamicModel(string p1, IDictionary<string, BinaryData> additionalProperties, in JsonPatch patch)
        {
            P1 = p1;
            _additionalBinaryDataProperties = additionalProperties;
            _patch = patch;
        }
#pragma warning restore SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.

        [JsonIgnoreAttribute]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [ExperimentalAttribute("SCME0001")]
        public ref JsonPatch Patch => ref _patch;

        public string P1 { get; set; }

        public IDictionary<string, BinaryData> AdditionalProperties => _additionalBinaryDataProperties;
    }
}
