// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace Sample.Models
{
    public abstract partial class Pet
    {
        [ExperimentalAttribute("SCME0001")]
        private JsonPatch _patch;

        private protected Pet(string kind, string name)
        {
            Kind = kind;
            Name = name;
        }

#pragma warning disable SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
        internal Pet(string kind, string name, in JsonPatch patch)
        {
            Kind = kind;
            Name = name;
            _patch = patch;
        }
#pragma warning restore SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.

        [JsonIgnoreAttribute]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [ExperimentalAttribute("SCME0001")]
        public ref JsonPatch Patch => ref _patch;

        internal string Kind { get; set; }

        public string Name { get; set; }
    }
}
