// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using Sample;

namespace Sample.Models
{
    public partial class Cat : Pet
    {
        public Cat(string name) : base("cat", name)
        {
            Argument.AssertNotNull(name, nameof(name));

        }

#pragma warning disable SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
        internal Cat(string kind, string name, in JsonPatch patch) : base(kind, name, patch)
        {
        }
#pragma warning restore SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
    }
}
