// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using Sample;

namespace Sample.Models
{
    public partial class Dog : Animal
    {
        [ExperimentalAttribute("SCME0001")]
        private JsonPatch _patch;

        public Dog(string species, bool barks) : base(species)
        {
            Argument.AssertNotNull(species, nameof(species));

            Barks = barks;
        }

#pragma warning disable SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
        internal Dog(string species, in JsonPatch patch, bool barks) : base(species, default)
        {
            Barks = barks;
            _patch = patch;
        }
#pragma warning restore SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.

        [JsonIgnoreAttribute]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [ExperimentalAttribute("SCME0001")]
        public ref JsonPatch Patch => ref _patch;

        public bool Barks { get; set; }
    }
}
