// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Sample.Models
{
    public partial class FooModel : MockInputModel
    {
        internal FooModel() : base(DiscriminatorValue.FooValue)
        {
        }

        internal FooModel(DiscriminatorValue discriminator, IDictionary<string, BinaryData> additionalBinaryDataProperties, IList<int> prop1) : base(prop1, discriminator, additionalBinaryDataProperties)
        {
        }

        public override virtual IList<int> Prop1 { get; }
    }
}
