// <auto-generated/>

#nullable disable

using System;
using Sample.Models;

namespace Sample
{
    public static partial class SampleModelFactory
    {
        public static MockInputModel MockInputModel(ReadOnlyMemory<byte> prop1 = default)
        {
            return new MockInputModel(prop1, additionalBinaryDataProperties: null);
        }
    }
}
