// <auto-generated/>

#nullable disable

using System.Threading;

namespace Sample
{
    public partial class TestClient
    {
        public virtual Animal GetAnimalClient()
        {
            return (Volatile.Read(ref _cachedAnimal) ?? (Interlocked.CompareExchange(ref _cachedAnimal, new Animal(), null) ?? _cachedAnimal));
        }
    }
}
