// <auto-generated/>

#nullable disable

using System.Threading;

namespace Sample
{
    public partial class Animal
    {
        public virtual Dog GetDogClient()
        {
            return (Volatile.Read(ref _cachedDog) ?? (Interlocked.CompareExchange(ref _cachedDog, new Dog(), null) ?? _cachedDog));
        }

        public virtual Cat GetCatClient()
        {
            return (Volatile.Read(ref _cachedCat) ?? (Interlocked.CompareExchange(ref _cachedCat, new Cat(), null) ?? _cachedCat));
        }

        public virtual HawkClient GetHawkClient()
        {
            return (Volatile.Read(ref _cachedHawkClient) ?? (Interlocked.CompareExchange(ref _cachedHawkClient, new HawkClient(), null) ?? _cachedHawkClient));
        }
    }
}
