// <auto-generated/>

#nullable disable

using System.Threading;

namespace Sample
{
    public partial class Dog
    {
        public virtual Husky GetHuskyClient()
        {
            return (Volatile.Read(ref _cachedHusky) ?? (Interlocked.CompareExchange(ref _cachedHusky, new Husky(), null) ?? _cachedHusky));
        }
    }
}
