// <auto-generated/>

#nullable disable

using System;

namespace Sample.Models
{
    internal static partial class MockInputModelExtensions
    {
        public static MockInputModel ToMockInputModel(this int value)
        {
            if ((value == 1))
            {
                return MockInputModel.Red;
            }
            if ((value == 2))
            {
                return MockInputModel.Green;
            }
            if ((value == 3))
            {
                return MockInputModel.SkyBlue;
            }
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown MockInputModel value.");
        }
    }
}
