// <auto-generated/>

#nullable disable

using System.ClientModel;
using System.ClientModel.Primitives;
using System.Collections.Generic;

namespace Sample
{
    internal partial class CatClientGetCatsAsyncCollectionResult : AsyncCollectionResult
    {
        private readonly CatClient _client;
        private readonly string _animalKind;
        private readonly RequestOptions _options;

        public CatClientGetCatsAsyncCollectionResult(CatClient client, string animalKind, RequestOptions options)
        {
            _client = client;
            _animalKind = animalKind;
            _options = options;
        }

        public override async IAsyncEnumerable<ClientResult> GetRawPagesAsync()
        {
            PipelineMessage message = _client.CreateGetCatsRequest(_animalKind, _options);
            yield return ClientResult.FromResponse(await _client.Pipeline.ProcessMessageAsync(message, _options).ConfigureAwait(false));
        }

        public override ContinuationToken GetContinuationToken(ClientResult page)
        {
            return null;
        }
    }
}
