// <auto-generated/>

#nullable disable

using System.ClientModel;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using Sample.Models;

namespace Sample
{
    internal partial class CatClientGetCatsCollectionResultOfT : CollectionResult<global::Sample.Models.Cat>
    {
        private readonly CatClient _client;
        private readonly string _animalKind;
        private readonly RequestOptions _options;

        public CatClientGetCatsCollectionResultOfT(CatClient client, string animalKind, RequestOptions options)
        {
            _client = client;
            _animalKind = animalKind;
            _options = options;
        }

        public override IEnumerable<ClientResult> GetRawPages()
        {
            PipelineMessage message = _client.CreateGetCatsRequest(_animalKind, _options);
            yield return ClientResult.FromResponse(_client.Pipeline.ProcessMessage(message, _options));
        }

        public override ContinuationToken GetContinuationToken(ClientResult page)
        {
            return null;
        }

        protected override IEnumerable<global::Sample.Models.Cat> GetValuesFromPage(ClientResult page)
        {
            return ((global::Sample.Models.Page)page).Cats;
        }
    }
}
