// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Text.Json;
using Sample;

namespace Sample.Models
{
    public readonly partial struct TestModel : IJsonModel<TestModel>, IJsonModel<object>
    {
        internal static TestModel DeserializeTestModel(JsonElement element, ModelReaderWriterOptions options)
        {
            if ((element.ValueKind == JsonValueKind.Null))
            {
                return default;
            }
            string stringProperty = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();
            foreach (var prop in element.EnumerateObject())
            {
                if (prop.NameEquals("stringProperty"u8))
                {
                    stringProperty = prop.Value.GetString();
                    continue;
                }
                if ((options.Format != "W"))
                {
                    additionalBinaryDataProperties.Add(prop.Name, BinaryData.FromString(prop.Value.GetRawText()));
                }
            }
            return new TestModel(stringProperty, additionalBinaryDataProperties);
        }
    }
}
