// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using System.Collections.Generic;

namespace Sample
{
    public partial class PipelineRequestHeadersExtensions
    {
        public static void Add(this PipelineRequestHeaders headers, string prefix, IDictionary<string, string> value)
        {
            foreach (var header in value)
            {
                headers.Add((prefix + header.Key), header.Value);
            }
        }
    }
}
