// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Text.Json;
using Sample.Models;

namespace Sample
{
    public partial class MockInputModel
    {
        internal static global::Sample.Models.MockInputModel DeserializeMockInputModel(JsonElement element, ModelReaderWriterOptions options)
        {
            if ((element.ValueKind == JsonValueKind.Null))
            {
                return null;
            }
            string prop1 = default;
            string prop2 = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();
            foreach (var prop in element.EnumerateObject())
            {
                if (prop.NameEquals("prop1"u8))
                {
                    DeserializationMethod(prop, ref prop1, options);
                    continue;
                }
                if (prop.NameEquals("prop2"u8))
                {
                    DeserializationMethod(prop, ref prop2, options);
                    continue;
                }
                if ((options.Format != "W"))
                {
                    additionalBinaryDataProperties.Add(prop.Name, BinaryData.FromString(prop.Value.GetRawText()));
                }
            }
            return new global::Sample.Models.MockInputModel(prop1, prop2, additionalBinaryDataProperties);
        }
    }
}
