// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Text.Json;
using Sample;

namespace Sample.Models
{
    public partial class Model : IJsonModel<Model>
    {
        protected virtual Model PersistableModelCreateCore(BinaryData data, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<Model>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    using (JsonDocument document = JsonDocument.Parse(data, ModelSerializationExtensions.JsonDocumentOptions))
                    {
                        return Model.DeserializeModel(document.RootElement, options);
                    }
                default:
                    throw new FormatException($"The model {nameof(Model)} does not support reading '{options.Format}' format.");
            }
        }

        protected virtual BinaryData PersistableModelWriteCore(ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<Model>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    return ModelReaderWriter.Write(this, options, SampleContext.Default);
                default:
                    throw new FormatException($"The model {nameof(Model)} does not support writing '{options.Format}' format.");
            }
        }

        BinaryData IPersistableModel<Model>.Write(ModelReaderWriterOptions options) => this.PersistableModelWriteCore(options);

        Model IPersistableModel<Model>.Create(BinaryData data, ModelReaderWriterOptions options) => this.PersistableModelCreateCore(data, options);

        string IPersistableModel<Model>.GetFormatFromOptions(ModelReaderWriterOptions options) => "J";

        void IJsonModel<Model>.Write(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            writer.WriteStartObject();
            this.JsonModelWriteCore(writer, options);
            writer.WriteEndObject();
        }

        protected virtual void JsonModelWriteCore(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<Model>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "J"))
            {
                throw new FormatException($"The model {nameof(Model)} does not support writing '{format}' format.");
            }
            writer.WritePropertyName("prop1"u8);
            writer.WriteStartArray();
            foreach (byte item in NewProp1.Span)
            {
                writer.WriteNumberValue(item);
            }
            writer.WriteEndArray();
            if (Optional.IsDefined(NewProp2))
            {
                writer.WritePropertyName("prop2"u8);
                writer.WriteStartArray();
                foreach (byte item in NewProp2.Value.Span)
                {
                    writer.WriteNumberValue(item);
                }
                writer.WriteEndArray();
            }
            if (((options.Format != "W") && (_additionalBinaryDataProperties != null)))
            {
                foreach (var item in _additionalBinaryDataProperties)
                {
                    writer.WritePropertyName(item.Key);
#if NET6_0_OR_GREATER
                    writer.WriteRawValue(item.Value);
#else
                    using (JsonDocument document = JsonDocument.Parse(item.Value))
                    {
                        JsonSerializer.Serialize(writer, document.RootElement);
                    }
#endif
                }
            }
        }

        Model IJsonModel<Model>.Create(ref Utf8JsonReader reader, ModelReaderWriterOptions options) => this.JsonModelCreateCore(ref reader, options);

        protected virtual Model JsonModelCreateCore(ref Utf8JsonReader reader, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<Model>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "J"))
            {
                throw new FormatException($"The model {nameof(Model)} does not support reading '{format}' format.");
            }
            using JsonDocument document = JsonDocument.ParseValue(ref reader);
            return Model.DeserializeModel(document.RootElement, options);
        }

        internal static Model DeserializeModel(JsonElement element, ModelReaderWriterOptions options)
        {
            if ((element.ValueKind == JsonValueKind.Null))
            {
                return null;
            }
            ReadOnlyMemory<byte> newProp1 = default;
            ReadOnlyMemory<byte>? newProp2 = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();
            foreach (var prop in element.EnumerateObject())
            {
                if (prop.NameEquals("prop1"u8))
                {
                    if ((prop.Value.ValueKind == JsonValueKind.Null))
                    {
                        continue;
                    }
                    int index = 0;
                    Byte[] array = new byte[prop.Value.GetArrayLength()];
                    foreach (var item in prop.Value.EnumerateArray())
                    {
                        array[index] = item.GetByte();
                        index++;
                    }
                    newProp1 = new ReadOnlyMemory<byte>(array);
                    continue;
                }
                if (prop.NameEquals("prop2"u8))
                {
                    if ((prop.Value.ValueKind == JsonValueKind.Null))
                    {
                        continue;
                    }
                    int index = 0;
                    Byte[] array = new byte[prop.Value.GetArrayLength()];
                    foreach (var item in prop.Value.EnumerateArray())
                    {
                        array[index] = item.GetByte();
                        index++;
                    }
                    newProp2 = new ReadOnlyMemory<byte>(array);
                    continue;
                }
                if ((options.Format != "W"))
                {
                    additionalBinaryDataProperties.Add(prop.Name, BinaryData.FromString(prop.Value.GetRawText()));
                }
            }
            return new Model(newProp1, newProp2, additionalBinaryDataProperties);
        }
    }
}
