// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using System.Collections.Generic;

namespace Sample
{
    public partial class TestClient
    {
        internal PipelineMessage CreateTestOperationRequest(IDictionary<string, string> metadata, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            if (((metadata != null) && !((metadata is ChangeTrackingDictionary<string, string> changeTrackingDictionary) && changeTrackingDictionary.IsUndefined)))
            {
                request.Headers.SetDelimited("x-ms-meta", metadata, null);
            }
            message.Apply(options);
            return message;
        }
    }
}
