// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;

namespace Sample
{
    public partial class TestClient
    {
        internal PipelineMessage CreateGetCatsRequest(string p1, IEnumerable<int> p2, IDictionary<string, int> p3, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendQuery("someOtherName", p1, true);
            if (((p2 != null) && !((p2 is ChangeTrackingList<int> changeTrackingList) && changeTrackingList.IsUndefined)))
            {
                uri.AppendQueryDelimited("p2", p2, " ", escape: true);
            }
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            if (((p3 != null) && !((p3 is ChangeTrackingDictionary<string, int> changeTrackingDictionary) && changeTrackingDictionary.IsUndefined)))
            {
                request.Headers.SetDelimited("p3", p3, null);
            }
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateNextGetCatsRequest(Uri nextPage, string p1, IEnumerable<int> p2, IDictionary<string, int> p3, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            if (nextPage.IsAbsoluteUri)
            {
                uri.Reset(nextPage);
            }
            else
            {
                uri.Reset(new Uri(_endpoint, nextPage));
            }
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }
    }
}
