// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;

namespace Sample
{
    public partial class TestClient
    {
        internal PipelineMessage CreateSampleOpRequest(string p1, string optionalParam, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/items/", false);
            uri.AppendPath(p1, true);
            uri.AppendQuery("comp", "copy", true);
            uri.AppendQuery("restype", "container", true);
            if ((optionalParam != null))
            {
                uri.AppendQuery("optionalParam", optionalParam, true);
            }
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "PUT", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            message.Apply(options);
            return message;
        }
    }
}
