// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;

namespace Sample
{
    public partial class TestClient
    {
        internal PipelineMessage CreateGetCatsRequest(string p1, string p2, string p3, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendQuery("someOtherName", p1, true);
            uri.AppendQuery("p2", p2, true);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("p3", p3);
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateNextGetCatsRequest(Uri nextPage, string p1, string p2, string p3, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            if (nextPage.IsAbsoluteUri)
            {
                uri.Reset(nextPage);
            }
            else
            {
                uri.Reset(new Uri(_endpoint, nextPage));
            }
            uri.AppendQuery("someOtherName", p1, true);
            uri.AppendQuery("p2", p2, true);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("p3", p3);
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }
    }
}
