// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;

namespace Sample
{
    public partial class TestClient
    {
        internal PipelineMessage CreateGetCatsRequest(string p1, string p2, string h1, int? maxPageSize, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendQuery("p1", p1, true);
            uri.AppendQuery("p2", p2, true);
            if ((maxPageSize != null))
            {
                uri.AppendQuery("maxpagesize", TypeFormatters.ConvertToString(maxPageSize), true);
            }
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("h1", h1);
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateNextGetCatsRequest(Uri nextPage, string p1, int? maxPageSize, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            if (nextPage.IsAbsoluteUri)
            {
                uri.Reset(nextPage);
            }
            else
            {
                uri.Reset(new Uri(_endpoint, nextPage));
            }
            uri.AppendQuery("p1", p1, true);
            if ((maxPageSize != null))
            {
                uri.UpdateQuery("maxpagesize", TypeFormatters.ConvertToString(maxPageSize));
            }
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }
    }
}
