// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;

namespace Sample
{
    public partial class TestClient
    {
        internal PipelineMessage CreateAbortCopyFromUrlRequest(string copyid, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/", false);
            uri.AppendQuery("comp", "copy", true);
            uri.AppendQuery("copyid", copyid, true);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "PUT", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            message.Apply(options);
            return message;
        }
    }
}
