// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using System.Collections.Generic;
using Sample.Models;

namespace Sample
{
    public partial class TestClient
    {
        internal PipelineMessage CreateSampleOpRequest(IEnumerable<string> p1Explode, IEnumerable<string> p1, IEnumerable<int> p2Explode, IEnumerable<int> p2, IDictionary<string, int> p3Explode, IDictionary<string, int> p3, IEnumerable<Foo> p4Explode, IEnumerable<IntFoo> p5Explode, IDictionary<string, Foo> p6Explode, IDictionary<string, IntFoo> p7Explode, IEnumerable<FloatFoo> p8Explode, IEnumerable<DoubleFoo> p9Explode, string optionalParam, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            if (((p1Explode != null) && !((p1Explode is ChangeTrackingList<string> changeTrackingList) && changeTrackingList.IsUndefined)))
            {
                foreach (var @param in p1Explode)
                {
                    uri.AppendQuery("p1Explode", @param, true);
                }
            }
            if (((p1 != null) && !((p1 is ChangeTrackingList<string> changeTrackingList0) && changeTrackingList0.IsUndefined)))
            {
                uri.AppendQueryDelimited("p1", p1, "|", escape: true);
            }
            if (((p2Explode != null) && !((p2Explode is ChangeTrackingList<int> changeTrackingList1) && changeTrackingList1.IsUndefined)))
            {
                foreach (var @param in p2Explode)
                {
                    uri.AppendQuery("p2Explode", @param, true);
                }
            }
            if (((p2 != null) && !((p2 is ChangeTrackingList<int> changeTrackingList2) && changeTrackingList2.IsUndefined)))
            {
                uri.AppendQueryDelimited("p2", p2, " ", escape: true);
            }
            if ((optionalParam != null))
            {
                uri.AppendQuery("optionalParam", optionalParam, true);
            }
            if (((p3Explode != null) && !((p3Explode is ChangeTrackingDictionary<string, int> changeTrackingDictionary) && changeTrackingDictionary.IsUndefined)))
            {
                foreach (var @param in p3Explode)
                {
                    uri.AppendQuery(@param.Key, @param.Value, true);
                }
            }
            if (((p3 != null) && !((p3 is ChangeTrackingDictionary<string, int> changeTrackingDictionary0) && changeTrackingDictionary0.IsUndefined)))
            {
                List<object> list = new List<object>();
                foreach (var @param in p3)
                {
                    list.Add(@param.Key);
                    list.Add(@param.Value);
                }
                uri.AppendQueryDelimited("p3", list, ",", escape: true);
            }
            if (((p4Explode != null) && !((p4Explode is ChangeTrackingList<Foo> changeTrackingList3) && changeTrackingList3.IsUndefined)))
            {
                foreach (var @param in p4Explode)
                {
                    uri.AppendQuery("p4Explode", @param.ToSerialString(), true);
                }
            }
            if (((p5Explode != null) && !((p5Explode is ChangeTrackingList<IntFoo> changeTrackingList4) && changeTrackingList4.IsUndefined)))
            {
                foreach (var @param in p5Explode)
                {
                    uri.AppendQuery("p5Explode", ((int)@param), true);
                }
            }
            if (((p6Explode != null) && !((p6Explode is ChangeTrackingDictionary<string, Foo> changeTrackingDictionary1) && changeTrackingDictionary1.IsUndefined)))
            {
                foreach (var @param in p6Explode)
                {
                    uri.AppendQuery(@param.Key, @param.ToSerialString(), true);
                }
            }
            if (((p7Explode != null) && !((p7Explode is ChangeTrackingDictionary<string, IntFoo> changeTrackingDictionary2) && changeTrackingDictionary2.IsUndefined)))
            {
                foreach (var @param in p7Explode)
                {
                    uri.AppendQuery(@param.Key, ((int)@param), true);
                }
            }
            if (((p8Explode != null) && !((p8Explode is ChangeTrackingList<FloatFoo> changeTrackingList5) && changeTrackingList5.IsUndefined)))
            {
                foreach (var @param in p8Explode)
                {
                    uri.AppendQuery("p8Explode", ((float)@param), true);
                }
            }
            if (((p9Explode != null) && !((p9Explode is ChangeTrackingList<DoubleFoo> changeTrackingList6) && changeTrackingList6.IsUndefined)))
            {
                foreach (var @param in p9Explode)
                {
                    uri.AppendQuery("p9Explode", ((double)@param), true);
                }
            }
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            message.Apply(options);
            return message;
        }
    }
}
