// <auto-generated/>

#nullable disable

using System.ClientModel;
using System.ClientModel.Primitives;

namespace Sample
{
    public partial class TestClient
    {
        private static PipelineMessageClassifier _pipelineMessageClassifier200;
        private static PipelineMessageClassifier _pipelineMessageClassifier200201202;
        private static PipelineMessageClassifier _pipelineMessageClassifier201;
        private static PipelineMessageClassifier _pipelineMessageClassifier202;
        private static PipelineMessageClassifier _pipelineMessageClassifier203;
        private static PipelineMessageClassifier _pipelineMessageClassifier204;
        private static PipelineMessageClassifier _pipelineMessageClassifier205;
        private static PipelineMessageClassifier _pipelineMessageClassifier206;

        private static PipelineMessageClassifier PipelineMessageClassifier200 => _pipelineMessageClassifier200 ??= PipelineMessageClassifier.Create(stackalloc ushort[] { 200 });

        private static PipelineMessageClassifier PipelineMessageClassifier200201202 => _pipelineMessageClassifier200201202 ??= PipelineMessageClassifier.Create(stackalloc ushort[] { 200, 201, 202 });

        private static PipelineMessageClassifier PipelineMessageClassifier201 => _pipelineMessageClassifier201 ??= PipelineMessageClassifier.Create(stackalloc ushort[] { 201 });

        private static PipelineMessageClassifier PipelineMessageClassifier202 => _pipelineMessageClassifier202 ??= PipelineMessageClassifier.Create(stackalloc ushort[] { 202 });

        private static PipelineMessageClassifier PipelineMessageClassifier203 => _pipelineMessageClassifier203 ??= PipelineMessageClassifier.Create(stackalloc ushort[] { 203 });

        private static PipelineMessageClassifier PipelineMessageClassifier204 => _pipelineMessageClassifier204 ??= PipelineMessageClassifier.Create(stackalloc ushort[] { 204 });

        private static PipelineMessageClassifier PipelineMessageClassifier205 => _pipelineMessageClassifier205 ??= PipelineMessageClassifier.Create(stackalloc ushort[] { 205 });

        private static PipelineMessageClassifier PipelineMessageClassifier206 => _pipelineMessageClassifier206 ??= PipelineMessageClassifier.Create(stackalloc ushort[] { 206 });

        internal PipelineMessage CreateTestOperation204Request(BinaryContent content, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier204);
            PipelineRequest request = message.Request;
            request.Content = content;
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateTestOperation205Request(BinaryContent content, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier205);
            PipelineRequest request = message.Request;
            request.Content = content;
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateTestOperation206Request(BinaryContent content, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier206);
            PipelineRequest request = message.Request;
            request.Content = content;
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateTestOperation200Request(BinaryContent content, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Content = content;
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateTestOperation202Request(BinaryContent content, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier202);
            PipelineRequest request = message.Request;
            request.Content = content;
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateTestOperation201Request(BinaryContent content, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier201);
            PipelineRequest request = message.Request;
            request.Content = content;
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateTestOperation203Request(BinaryContent content, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier203);
            PipelineRequest request = message.Request;
            request.Content = content;
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateTestOperation200201202Request(BinaryContent content, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200201202);
            PipelineRequest request = message.Request;
            request.Content = content;
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateDuplicateTestOperation200201202Request(BinaryContent content, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200201202);
            PipelineRequest request = message.Request;
            request.Content = content;
            message.Apply(options);
            return message;
        }
    }
}
