// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;

namespace Sample
{
    public partial class TestClient
    {
        internal PipelineMessage CreateSingleServiceMethodInputClientOperationRequest(RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("accept", "image/png");
            message.Apply(options);
            return message;
        }
    }
}
