// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Sample;

namespace Sample.Models
{
    public readonly partial struct TestModel
    {
        private readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        public TestModel(string requiredString, int requiredInt)
        {
            Argument.AssertNotNull(requiredString, nameof(requiredString));

            RequiredString = requiredString;
            RequiredInt = requiredInt;
        }

        internal TestModel(string requiredString, int requiredInt, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            RequiredString = requiredString;
            RequiredInt = requiredInt;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        public string RequiredString { get; }

        public int RequiredInt { get; }
    }
}
