// <auto-generated/>

#nullable disable

using System;
using System.Runtime.InteropServices;
using System.Text.Json;

namespace Sample
{
    public partial class ModelSerializationExtensions
    {
        public static BinaryData GetUtf8Bytes(this JsonElement element)
        {
#if NET9_0_OR_GREATER
            return new BinaryData(JsonMarshal.GetRawUtf8Value(element).ToArray());
#else
            return BinaryData.FromString(element.GetRawText());
#endif
        }
    }
}
