// <auto-generated/>

#nullable disable

using System;
using System.Text;

namespace Sample
{
    public partial class ModelSerializationExtensions
    {
        public static string GetFirstPropertyName(this ReadOnlySpan<byte> jsonPath, out int bytesConsumed)
        {
            ReadOnlySpan<byte> local = jsonPath;
            for (bytesConsumed = 0; (bytesConsumed < local.Length); bytesConsumed++)
            {
                byte current = local[bytesConsumed];
                if ((current == '.'))
                {
                    break;
                }
                else
                {
                    if (((current == '\'') || (current == '"')))
                    {
                        if ((((bytesConsumed + 1) < local.Length) && (local[(bytesConsumed + 1)] == ']')))
                        {
                            break;
                        }
                    }
                }
            }

            string key;
#if NET6_0_OR_GREATER
            key = Encoding.UTF8.GetString(local.Slice(0, bytesConsumed));
#else
            key = Encoding.UTF8.GetString(local.Slice(0, bytesConsumed).ToArray());
#endif
            (bytesConsumed += (jsonPath.Length - local.Length));
            return key;
        }
    }
}
