// <auto-generated/>

#nullable disable

using System;

namespace Sample
{
    public partial class ModelSerializationExtensions
    {
        public static ReadOnlySpan<byte> GetRemainder(this ReadOnlySpan<byte> jsonPath, int index)
        {
            return (index >= jsonPath.Length) ? ReadOnlySpan<byte>.Empty : (jsonPath[index] == '.') ? jsonPath.Slice(index) : jsonPath.Slice((index + 2));
        }
    }
}
