// <auto-generated/>

#nullable disable

using System;

namespace Sample
{
    public partial class ModelSerializationExtensions
    {
        public static ReadOnlySpan<byte> SliceToStartOfPropertyName(this ReadOnlySpan<byte> jsonPath)
        {
            ReadOnlySpan<byte> local = jsonPath;
            if ((local.Length < 3))
            {
                return ReadOnlySpan<byte>.Empty;
            }
            if ((local[0] != '$'))
            {
                return ReadOnlySpan<byte>.Empty;
            }
            return (((local.Length >= 4) && (local[1] == '[')) && ((local[2] == '\'') || (local[2] == '"'))) ? local.Slice(3) : ReadOnlySpan<byte>.Empty;
        }
    }
}
