// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Text.Json;
using Sample;

namespace Sample.Models
{
    public partial class Tree : Plant, IJsonModel<Tree>
    {
        internal Tree()
        {
        }

        protected override Plant PersistableModelCreateCore(BinaryData data, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<Tree>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    using (JsonDocument document = JsonDocument.Parse(data, ModelSerializationExtensions.JsonDocumentOptions))
                    {
                        return Tree.DeserializeTree(document.RootElement, options);
                    }
                default:
                    throw new FormatException($"The model {nameof(Tree)} does not support reading '{options.Format}' format.");
            }
        }

        protected override BinaryData PersistableModelWriteCore(ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<Tree>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    return ModelReaderWriter.Write(this, options, SampleContext.Default);
                default:
                    throw new FormatException($"The model {nameof(Tree)} does not support writing '{options.Format}' format.");
            }
        }

        BinaryData IPersistableModel<Tree>.Write(ModelReaderWriterOptions options) => this.PersistableModelWriteCore(options);

        Tree IPersistableModel<Tree>.Create(BinaryData data, ModelReaderWriterOptions options) => ((Tree)this.PersistableModelCreateCore(data, options));

        string IPersistableModel<Tree>.GetFormatFromOptions(ModelReaderWriterOptions options) => "J";

        void IJsonModel<Tree>.Write(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            writer.WriteStartObject();
            this.JsonModelWriteCore(writer, options);
            writer.WriteEndObject();
        }

        protected override void JsonModelWriteCore(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<Tree>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "J"))
            {
                throw new FormatException($"The model {nameof(Tree)} does not support writing '{format}' format.");
            }
            base.JsonModelWriteCore(writer, options);
            writer.WritePropertyName("treeType"u8);
            writer.WriteStringValue(TreeType);
        }

        Tree IJsonModel<Tree>.Create(ref Utf8JsonReader reader, ModelReaderWriterOptions options) => ((Tree)this.JsonModelCreateCore(ref reader, options));

        protected override Plant JsonModelCreateCore(ref Utf8JsonReader reader, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<Tree>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "J"))
            {
                throw new FormatException($"The model {nameof(Tree)} does not support reading '{format}' format.");
            }
            using JsonDocument document = JsonDocument.ParseValue(ref reader);
            return Tree.DeserializeTree(document.RootElement, options);
        }

        internal static Tree DeserializeTree(JsonElement element, ModelReaderWriterOptions options)
        {
            if ((element.ValueKind == JsonValueKind.Null))
            {
                return null;
            }
            if (element.TryGetProperty("treeType"u8, out JsonElement discriminator))
            {
                switch (discriminator.GetString())
                {
                    case "oak":
                        return OakTree.DeserializeOakTree(element, options);
                }
            }
            return UnknownTree.DeserializeUnknownTree(element, options);
        }
    }
}
