// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Threading.Tasks;
using Sample.Models;

namespace Sample
{
    internal partial class CatClientGetCatsAsyncCollectionResultOfT : AsyncCollectionResult<Cat>
    {
        private readonly CatClient _client;
        private readonly string _myToken;
        private readonly RequestOptions _options;

        public CatClientGetCatsAsyncCollectionResultOfT(CatClient client, string myToken, RequestOptions options)
        {
            _client = client;
            _myToken = myToken;
            _options = options;
        }

        public override async IAsyncEnumerable<ClientResult> GetRawPagesAsync()
        {
            PipelineMessage message = _client.CreateGetCatsRequest(_myToken, _options);
            string nextToken = null;
            while (true)
            {
                ClientResult result = ClientResult.FromResponse(await _client.Pipeline.ProcessMessageAsync(message, _options).ConfigureAwait(false));
                yield return result;

                nextToken = ((Page)result).NextPage;
                if (string.IsNullOrEmpty(nextToken))
                {
                    yield break;
                }
                message = _client.CreateGetCatsRequest(nextToken, _options);
            }
        }

        public override ContinuationToken GetContinuationToken(ClientResult page)
        {
            string nextPage = ((Page)page).NextPage;
            if (!string.IsNullOrEmpty(nextPage))
            {
                return ContinuationToken.FromBytes(BinaryData.FromString(nextPage));
            }
            else
            {
                return null;
            }
        }

        protected override async IAsyncEnumerable<Cat> GetValuesFromPageAsync(ClientResult page)
        {
            foreach (Cat item in ((Page)page).Cats)
            {
                yield return item;
                await Task.Yield();
            }
        }
    }
}
