// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using Sample.Models;

namespace Sample
{
    internal partial class CatClientGetCatsCollectionResult : CollectionResult
    {
        private readonly CatClient _client;
        private readonly string _myToken;
        private readonly RequestOptions _options;

        public CatClientGetCatsCollectionResult(CatClient client, string myToken, RequestOptions options)
        {
            _client = client;
            _myToken = myToken;
            _options = options;
        }

        public override IEnumerable<ClientResult> GetRawPages()
        {
            PipelineMessage message = _client.CreateGetCatsRequest(_myToken, _options);
            string nextToken = null;
            while (true)
            {
                ClientResult result = ClientResult.FromResponse(_client.Pipeline.ProcessMessage(message, _options));
                yield return result;

                nextToken = ((global::Sample.Models.Page)result).NestedNext?.NextPage;
                if (string.IsNullOrEmpty(nextToken))
                {
                    yield break;
                }
                message = _client.CreateGetCatsRequest(nextToken, _options);
            }
        }

        public override ContinuationToken GetContinuationToken(ClientResult page)
        {
            string nextPage = ((global::Sample.Models.Page)page).NestedNext?.NextPage;
            if (!string.IsNullOrEmpty(nextPage))
            {
                return ContinuationToken.FromBytes(BinaryData.FromString(nextPage));
            }
            else
            {
                return null;
            }
        }
    }
}
