// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Threading.Tasks;
using Sample.Models;

namespace Sample
{
    internal partial class CatClientGetCatsAsyncCollectionResultOfT : AsyncCollectionResult<Cat>
    {
        private readonly CatClient _client;
        private readonly RequestOptions _options;

        public CatClientGetCatsAsyncCollectionResultOfT(CatClient client, RequestOptions options)
        {
            _client = client;
            _options = options;
        }

        public override async IAsyncEnumerable<ClientResult> GetRawPagesAsync()
        {
            PipelineMessage message = _client.CreateGetCatsRequest(_options);
            Uri nextPageUri = null;
            while (true)
            {
                ClientResult result = ClientResult.FromResponse(await _client.Pipeline.ProcessMessageAsync(message, _options).ConfigureAwait(false));
                yield return result;

                nextPageUri = ((Page)result).NestedNext?.NextCat;
                if ((nextPageUri == null))
                {
                    yield break;
                }
                message = _client.CreateNextGetCatsRequest(nextPageUri, _options);
            }
        }

        public override ContinuationToken GetContinuationToken(ClientResult page)
        {
            Uri nextPage = ((Page)page).NestedNext?.NextCat;
            if ((nextPage != null))
            {
                return ContinuationToken.FromBytes(BinaryData.FromString(nextPage.IsAbsoluteUri ? nextPage.AbsoluteUri : nextPage.OriginalString));
            }
            else
            {
                return null;
            }
        }

        protected override async IAsyncEnumerable<Cat> GetValuesFromPageAsync(ClientResult page)
        {
            foreach (Cat item in ((Page)page).NestedItems?.Cats)
            {
                yield return item;
                await Task.Yield();
            }
        }
    }
}
