// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Collections.Generic;

namespace Sample
{
    internal partial class CatClientGetCatsCollectionResult : CollectionResult
    {
        private readonly CatClient _client;
        private readonly RequestOptions _options;

        public CatClientGetCatsCollectionResult(CatClient client, RequestOptions options)
        {
            _client = client;
            _options = options;
        }

        public override IEnumerable<ClientResult> GetRawPages()
        {
            PipelineMessage message = _client.CreateGetCatsRequest(_options);
            Uri nextPageUri = null;
            while (true)
            {
                ClientResult result = ClientResult.FromResponse(_client.Pipeline.ProcessMessage(message, _options));
                yield return result;

                if ((result.GetRawResponse().Headers.TryGetValue("nextCat", out string value) && !string.IsNullOrEmpty(value)))
                {
                    nextPageUri = new Uri(value, UriKind.RelativeOrAbsolute);
                }
                else
                {
                    yield break;
                }
                message = _client.CreateNextGetCatsRequest(nextPageUri, _options);
            }
        }

        public override ContinuationToken GetContinuationToken(ClientResult page)
        {
            if ((page.GetRawResponse().Headers.TryGetValue("nextCat", out string value) && !string.IsNullOrEmpty(value)))
            {
                return ContinuationToken.FromBytes(BinaryData.FromString(value));
            }
            else
            {
                return null;
            }
        }
    }
}
