// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Sample.Models
{
    public partial class MockInputModel
    {
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        internal MockInputModel()
        {
        }

        internal MockInputModel(string myField, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            _myField = myField;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }
    }
}
