// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Text.Json;
using Sample;

namespace Sample.Models
{
    public partial class MockInputModel : IJsonModel<MockInputModel>
    {
        protected virtual MockInputModel PersistableModelCreateCore(BinaryData data, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<MockInputModel>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    using (JsonDocument document = JsonDocument.Parse(data, ModelSerializationExtensions.JsonDocumentOptions))
                    {
                        return MockInputModel.DeserializeMockInputModel(document.RootElement, options);
                    }
                default:
                    throw new FormatException($"The model {nameof(MockInputModel)} does not support reading '{options.Format}' format.");
            }
        }

        protected virtual BinaryData PersistableModelWriteCore(ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<MockInputModel>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    return ModelReaderWriter.Write(this, options, SampleContext.Default);
                default:
                    throw new FormatException($"The model {nameof(MockInputModel)} does not support writing '{options.Format}' format.");
            }
        }

        BinaryData IPersistableModel<MockInputModel>.Write(ModelReaderWriterOptions options) => this.PersistableModelWriteCore(options);

        MockInputModel IPersistableModel<MockInputModel>.Create(BinaryData data, ModelReaderWriterOptions options) => this.PersistableModelCreateCore(data, options);

        string IPersistableModel<MockInputModel>.GetFormatFromOptions(ModelReaderWriterOptions options) => "J";

        void IJsonModel<MockInputModel>.Write(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            writer.WriteStartObject();
            this.JsonModelWriteCore(writer, options);
            writer.WriteEndObject();
        }

        protected virtual void JsonModelWriteCore(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<MockInputModel>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "J"))
            {
                throw new FormatException($"The model {nameof(MockInputModel)} does not support writing '{format}' format.");
            }
            if (Optional.IsDefined(Prop1))
            {
                writer.WritePropertyName("prop1"u8);
                writer.WriteObjectValue<object>(Prop1, options);
            }
            if (((options.Format != "W") && (_additionalBinaryDataProperties != null)))
            {
                foreach (var item in _additionalBinaryDataProperties)
                {
                    writer.WritePropertyName(item.Key);
#if NET6_0_OR_GREATER
                    writer.WriteRawValue(item.Value);
#else
                    using (JsonDocument document = JsonDocument.Parse(item.Value))
                    {
                        JsonSerializer.Serialize(writer, document.RootElement);
                    }
#endif
                }
            }
        }

        MockInputModel IJsonModel<MockInputModel>.Create(ref Utf8JsonReader reader, ModelReaderWriterOptions options) => this.JsonModelCreateCore(ref reader, options);

        protected virtual MockInputModel JsonModelCreateCore(ref Utf8JsonReader reader, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<MockInputModel>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "J"))
            {
                throw new FormatException($"The model {nameof(MockInputModel)} does not support reading '{format}' format.");
            }
            using JsonDocument document = JsonDocument.ParseValue(ref reader);
            return MockInputModel.DeserializeMockInputModel(document.RootElement, options);
        }

        internal static MockInputModel DeserializeMockInputModel(JsonElement element, ModelReaderWriterOptions options)
        {
            if ((element.ValueKind == JsonValueKind.Null))
            {
                return null;
            }
            object prop1 = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();
            foreach (var prop in element.EnumerateObject())
            {
                if (prop.NameEquals("prop1"u8))
                {
                    if ((prop.Value.ValueKind == JsonValueKind.Null))
                    {
                        continue;
                    }
                    prop1 = prop.Value.GetObject();
                    continue;
                }
                if ((options.Format != "W"))
                {
                    additionalBinaryDataProperties.Add(prop.Name, BinaryData.FromString(prop.Value.GetRawText()));
                }
            }
            return new MockInputModel(prop1, additionalBinaryDataProperties);
        }
    }
}
