// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Xml.Linq;
using Sample.Models;

namespace Sample
{
    public partial class TestXmlModel
    {
        internal static global::Sample.Models.TestXmlModel DeserializeTestXmlModel(XElement element, ModelReaderWriterOptions options)
        {
            if ((element == null))
            {
                return null;
            }

            string name = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();

            foreach (var child in element.Elements())
            {
                string localName = child.Name.LocalName;
                if ((localName == "Name"))
                {
                    name = child.ToString();
                    continue;
                }
            }
            return new global::Sample.Models.TestXmlModel(name, additionalBinaryDataProperties);
        }
    }
}
