// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.IO;
using System.Text.Json;
using System.Xml.Linq;
using Sample.Models;

namespace Sample
{
    public partial class TestModel
    {
        public static explicit operator TestModel(ClientResult result)
        {
            using PipelineResponse response = result.GetRawResponse();

            if ((response.Headers.TryGetValue("Content-Type", out string value) && value.StartsWith("application/json", StringComparison.OrdinalIgnoreCase)))
            {
                using JsonDocument document = JsonDocument.Parse(response.Content, ModelSerializationExtensions.JsonDocumentOptions);
                return global::Sample.Models.TestModel.DeserializeTestModel(document.RootElement, ModelSerializationExtensions.WireOptions);
            }

            using Stream stream = response.ContentStream;
            if ((stream == null))
            {
                return default;
            }

            return global::Sample.Models.TestModel.DeserializeTestModel(XElement.Load(stream, LoadOptions.PreserveWhitespace), ModelSerializationExtensions.WireOptions);
        }
    }
}
