// <auto-generated/>

#nullable disable

using System.ClientModel;
using System.ClientModel.Primitives;
using System.IO;
using System.Xml.Linq;
using Sample.Models;

namespace Sample
{
    public partial class TestXmlModel
    {
        public static explicit operator TestXmlModel(ClientResult result)
        {
            using PipelineResponse response = result.GetRawResponse();
            using Stream stream = response.ContentStream;
            if ((stream == null))
            {
                return default;
            }

            return TestXmlModel.DeserializeTestXmlModel(XElement.Load(stream, LoadOptions.PreserveWhitespace), ModelSerializationExtensions.WireOptions);
        }
    }
}
