// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using System.Xml.Linq;
using Sample.Models;

namespace Sample
{
    public partial class Pet
    {
        internal static Pet DeserializePet(XElement element, ModelReaderWriterOptions options)
        {
            if ((element == null))
            {
                return null;
            }

            XElement discriminatorElement = element.Element("kind");
            if ((discriminatorElement != null))
            {
                switch (((string)discriminatorElement))
                {
                    case "cat":
                        return Cat.DeserializeCat(element, options);
                }
            }
            return UnknownPet.DeserializeUnknownPet(element, options);
        }
    }
}
