// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.IO;
using System.Xml.Linq;
using Sample;

namespace Sample.Models
{
    public partial class TestXmlModel : IPersistableModel<TestXmlModel>
    {
        internal TestXmlModel()
        {
        }

        protected virtual TestXmlModel PersistableModelCreateCore(BinaryData data, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<TestXmlModel>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "X":
                    using (Stream dataStream = data.ToStream())
                    {
                        return TestXmlModel.DeserializeTestXmlModel(XElement.Load(dataStream, LoadOptions.PreserveWhitespace), options);
                    }
                default:
                    throw new FormatException($"The model {nameof(TestXmlModel)} does not support reading '{options.Format}' format.");
            }
        }

        internal static TestXmlModel DeserializeTestXmlModel(XElement element, ModelReaderWriterOptions options)
        {
            if ((element == null))
            {
                return null;
            }

            IList<int> counts = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();

            foreach (var child in element.Elements())
            {
                string localName = child.Name.LocalName;
                if ((localName == "counts"))
                {
                    List<int> array = new List<int>();
                    foreach (var e in child.Elements("int32"))
                    {
                        array.Add(((int)e));
                    }
                    counts = array;
                    continue;
                }
            }
            return new TestXmlModel(counts, additionalBinaryDataProperties);
        }
    }
}
