// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Xml.Linq;
using Sample.Models;

namespace Sample
{
    public partial class TestXmlModel
    {
        internal static TestXmlModel DeserializeTestXmlModel(XElement element, ModelReaderWriterOptions options)
        {
            if ((element == null))
            {
                return null;
            }

            XNamespace labelNs = "https://example.com/ns1";

            string id = default;
            string label = default;
            string name = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();

            foreach (var attr in element.Attributes())
            {
                string localName = attr.Name.LocalName;
                XNamespace ns = attr.Name.Namespace;

                if ((localName == "id"))
                {
                    id = ((string)attr);
                    continue;
                }
                if (((localName == "label") && (ns == labelNs)))
                {
                    label = ((string)attr);
                    continue;
                }
            }

            foreach (var child in element.Elements())
            {
                string localName = child.Name.LocalName;
                XNamespace ns = child.Name.Namespace;

                if ((localName == "name"))
                {
                    name = ((string)child);
                    continue;
                }
            }
            return new TestXmlModel(id, label, name, additionalBinaryDataProperties);
        }
    }
}
