// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.IO;
using System.Xml.Linq;
using Sample;

namespace Sample.Models
{
    public partial class OuterModel : IPersistableModel<OuterModel>
    {
        protected virtual OuterModel PersistableModelCreateCore(BinaryData data, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<OuterModel>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "X":
                    using (Stream dataStream = data.ToStream())
                    {
                        return OuterModel.DeserializeOuterModel(XElement.Load(dataStream, LoadOptions.PreserveWhitespace), options);
                    }
                default:
                    throw new FormatException($"The model {nameof(OuterModel)} does not support reading '{options.Format}' format.");
            }
        }

        internal static OuterModel DeserializeOuterModel(XElement element, ModelReaderWriterOptions options)
        {
            if ((element == null))
            {
                return null;
            }

            InnerModel inner = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();

            foreach (var child in element.Elements())
            {
                string localName = child.Name.LocalName;
                if ((localName == "inner"))
                {
                    inner = InnerModel.DeserializeInnerModel(child, options);
                    continue;
                }
            }
            return new OuterModel(inner, additionalBinaryDataProperties);
        }
    }
}
