// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Xml.Linq;
using Sample.Models;

namespace Sample
{
    public partial class Cat
    {
        internal static global::Sample.Models.Cat DeserializeCat(XElement element, ModelReaderWriterOptions options)
        {
            if ((element == null))
            {
                return null;
            }

            string kind = "cat";
            string name = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();
            bool meows = default;

            foreach (var child in element.Elements())
            {
                string localName = child.Name.LocalName;
                if ((localName == "kind"))
                {
                    kind = ((string)child);
                    continue;
                }
                if ((localName == "name"))
                {
                    name = ((string)child);
                    continue;
                }
                if ((localName == "meows"))
                {
                    meows = ((bool)child);
                    continue;
                }
            }
            return new global::Sample.Models.Cat(kind, name, additionalBinaryDataProperties, meows);
        }
    }
}
