// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Diagnostics.CodeAnalysis;

namespace Sample
{
    public partial class TestClient
    {
        private readonly Uri _endpoint;

        protected TestClient()
        {
        }

        public TestClient(Uri endpoint) : this(endpoint, new TestClientOptions())
        {
        }

        internal TestClient(AuthenticationPolicy authenticationPolicy, Uri endpoint, TestClientOptions options)
        {
            Argument.AssertNotNull(endpoint, nameof(endpoint));

            options ??= new TestClientOptions();

            _endpoint = endpoint;
            if ((authenticationPolicy != null))
            {
                Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(TestClient).Assembly), authenticationPolicy }, Array.Empty<PipelinePolicy>());
            }
            else
            {
                Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(TestClient).Assembly) }, Array.Empty<PipelinePolicy>());
            }
        }

        public TestClient(Uri endpoint, TestClientOptions options) : this(null, endpoint, options)
        {
        }

        [ExperimentalAttribute("SCME0002")]
        public TestClient(TestClientSettings settings) : this(AuthenticationPolicy.Create(settings), settings?.Endpoint, settings?.Options)
        {
        }

        public ClientPipeline Pipeline { get; }
    }
}
