// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Configuration;

namespace Sample
{
    [ExperimentalAttribute("SCME0002")]
    public partial class TestClientSettings : ClientSettings
    {
        public Uri Endpoint { get; set; }

        public TestClientOptions Options { get; set; }

        protected override void BindCore(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
        {
            if (Uri.TryCreate(section["Endpoint"], UriKind.Absolute, out Uri endpoint))
            {
                this.Endpoint = endpoint;
            }
            global::Microsoft.Extensions.Configuration.IConfigurationSection optionsSection = section.GetSection("Options");
            if (optionsSection.Exists())
            {
                this.Options = new TestClientOptions(optionsSection);
            }
        }
    }
}
