// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Configuration;

namespace Sample
{
    [ExperimentalAttribute("SCME0002")]
    public partial class TestClientSettings : ClientSettings
    {
        public string FullyQualifiedNamespace { get; set; }

        public TestClientOptions Options { get; set; }

        protected override void BindCore(IConfigurationSection section)
        {
            string fullyQualifiedNamespace = section["FullyQualifiedNamespace"];
            if (!string.IsNullOrEmpty(fullyQualifiedNamespace))
            {
                this.FullyQualifiedNamespace = fullyQualifiedNamespace;
            }
            IConfigurationSection optionsSection = section.GetSection("Options");
            if (optionsSection.Exists())
            {
                this.Options = new TestClientOptions(optionsSection);
            }
        }
    }
}
