// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Configuration;

namespace Sample
{
    [ExperimentalAttribute("SCME0002")]
    public partial class TestClientSettings : ClientSettings
    {
        public string Endpoint { get; set; }

        public TestClientOptions Options { get; set; }

        protected override void BindCore(global::Microsoft.Extensions.Configuration.IConfigurationSection section)
        {
            string endpoint = section["Endpoint"];
            if (!string.IsNullOrEmpty(endpoint))
            {
                this.Endpoint = endpoint;
            }
            global::Microsoft.Extensions.Configuration.IConfigurationSection optionsSection = section.GetSection("Options");
            if (optionsSection.Exists())
            {
                this.Options = new TestClientOptions(optionsSection);
            }
        }
    }
}
