// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.IO;
using System.Xml;
using Sample.Models;

namespace Sample
{
    public partial class TestXmlModel
    {
        protected virtual BinaryData PersistableModelWriteCore(ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<TestXmlModel>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "X":
                    using (MemoryStream stream = new MemoryStream(256))
                    {
                        using (XmlWriter writer = XmlWriter.Create(stream, ModelSerializationExtensions.XmlWriterSettings))
                        {
                            this.WriteXml(writer, options, "TestXmlModel");
                        }
                        if ((stream.Position > int.MaxValue))
                        {
                            return BinaryData.FromStream(stream);
                        }
                        else
                        {
                            return new BinaryData(stream.GetBuffer().AsMemory(0, ((int)stream.Position)));
                        }
                    }
                default:
                    throw new FormatException($"The model {nameof(TestXmlModel)} does not support writing '{options.Format}' format.");
            }
        }
    }
}
