// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Xml;
using Sample.Models;

namespace Sample
{
    public partial class TestXmlModel
    {
        internal virtual void XmlModelWriteCore(XmlWriter writer, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<global::Sample.Models.TestXmlModel>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "X"))
            {
                throw new FormatException($"The model {nameof(global::Sample.Models.TestXmlModel)} does not support writing '{format}' format.");
            }

            if (Optional.IsDefined(Name))
            {
                writer.WriteStartElement("Name");
                writer.WriteValue(Name.ToString());
                writer.WriteEndElement();
            }
        }
    }
}
