// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;

namespace Sample.Models
{
    public partial class TestXmlModel : IPersistableModel<TestXmlModel>
    {
        internal TestXmlModel()
        {
        }

        BinaryData IPersistableModel<TestXmlModel>.Write(ModelReaderWriterOptions options) => this.PersistableModelWriteCore(options);

        TestXmlModel IPersistableModel<TestXmlModel>.Create(BinaryData data, ModelReaderWriterOptions options) => this.PersistableModelCreateCore(data, options);

        string IPersistableModel<TestXmlModel>.GetFormatFromOptions(ModelReaderWriterOptions options) => "X";
    }
}
