// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Xml;
using Sample.Models;

namespace Sample
{
    public partial class Cat
    {
        BinaryData IPersistableModel<global::Sample.Models.Cat>.Write(ModelReaderWriterOptions options) => this.PersistableModelWriteCore(options);

        private void WriteXml(XmlWriter writer, ModelReaderWriterOptions options, string nameHint)
        {
            if ((nameHint != null))
            {
                writer.WriteStartElement(nameHint);
            }

            this.XmlModelWriteCore(writer, options);

            if ((nameHint != null))
            {
                writer.WriteEndElement();
            }
        }

        internal override void XmlModelWriteCore(XmlWriter writer, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<global::Sample.Models.Cat>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "X"))
            {
                throw new FormatException($"The model {nameof(global::Sample.Models.Cat)} does not support writing '{format}' format.");
            }

            base.XmlModelWriteCore(writer, options);
            writer.WriteStartElement("meows");
            writer.WriteValue(Meows);
            writer.WriteEndElement();
        }
    }
}
