// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.IO;
using System.Xml;
using Sample;

namespace Sample.Models
{
    public partial class OuterModel : IPersistableModel<OuterModel>
    {
        protected virtual BinaryData PersistableModelWriteCore(ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<OuterModel>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "X":
                    using (MemoryStream stream = new MemoryStream(256))
                    {
                        using (XmlWriter writer = XmlWriter.Create(stream, ModelSerializationExtensions.XmlWriterSettings))
                        {
                            this.WriteXml(writer, options, "OuterModel");
                        }
                        if ((stream.Position > int.MaxValue))
                        {
                            return BinaryData.FromStream(stream);
                        }
                        else
                        {
                            return new BinaryData(stream.GetBuffer().AsMemory(0, ((int)stream.Position)));
                        }
                    }
                default:
                    throw new FormatException($"The model {nameof(OuterModel)} does not support writing '{options.Format}' format.");
            }
        }

        BinaryData IPersistableModel<OuterModel>.Write(ModelReaderWriterOptions options) => this.PersistableModelWriteCore(options);

        private void WriteXml(XmlWriter writer, ModelReaderWriterOptions options, string nameHint)
        {
            if ((nameHint != null))
            {
                writer.WriteStartElement(nameHint);
            }

            this.XmlModelWriteCore(writer, options);

            if ((nameHint != null))
            {
                writer.WriteEndElement();
            }
        }

        internal virtual void XmlModelWriteCore(XmlWriter writer, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<OuterModel>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "X"))
            {
                throw new FormatException($"The model {nameof(OuterModel)} does not support writing '{format}' format.");
            }

            if (Optional.IsDefined(Inner))
            {
                writer.WriteStartElement("inner");
                writer.WriteObjectValue<InnerModel>(Inner, options);
                writer.WriteEndElement();
            }
        }
    }
}
