// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Xml;
using Sample.Models;

namespace Sample
{
    public partial class TestXmlModel
    {
        BinaryData IPersistableModel<TestXmlModel>.Write(ModelReaderWriterOptions options) => this.PersistableModelWriteCore(options);

        private void WriteXml(XmlWriter writer, ModelReaderWriterOptions options, string nameHint)
        {
            if ((nameHint != null))
            {
                writer.WriteStartElement(nameHint);
            }

            this.XmlModelWriteCore(writer, options);

            if ((nameHint != null))
            {
                writer.WriteEndElement();
            }
        }

        internal virtual void XmlModelWriteCore(XmlWriter writer, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<TestXmlModel>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "X"))
            {
                throw new FormatException($"The model {nameof(TestXmlModel)} does not support writing '{format}' format.");
            }

            writer.WriteStartAttribute("id");
            writer.WriteValue(Id);
            writer.WriteEndAttribute();
            writer.WriteAttributeString("ns1", "label", "https://example.com/ns1", Label);
            writer.WriteStartElement("name");
            writer.WriteValue(Name);
            writer.WriteEndElement();
        }
    }
}
