// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using Sample.Models;

namespace Sample
{
    public partial class DynamicModel
    {
        internal static global::Sample.Models.DynamicModel DeserializeDynamicModel(JsonElement element, BinaryData data, ModelReaderWriterOptions options)
        {
            if ((element.ValueKind == JsonValueKind.Null))
            {
                return null;
            }
            IDictionary<string, global::Sample.Models.Cat> cats = default;
            IDictionary<string, string> names = default;
            IDictionary<string, string> optionalNames = default;
#pragma warning disable SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
            JsonPatch patch = new JsonPatch((data is null) ? ReadOnlyMemory<byte>.Empty : data.ToMemory());
#pragma warning restore SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
            foreach (var prop in element.EnumerateObject())
            {
                if (prop.NameEquals("cats"u8))
                {
                    if ((prop.Value.ValueKind == JsonValueKind.Null))
                    {
                        continue;
                    }
                    Dictionary<string, global::Sample.Models.Cat> dictionary = new Dictionary<string, global::Sample.Models.Cat>();
                    foreach (var prop0 in prop.Value.EnumerateObject())
                    {
                        dictionary.Add(prop0.Name, global::Sample.Models.Cat.DeserializeCat(prop0.Value, options));
                    }
                    cats = dictionary;
                    continue;
                }
                if (prop.NameEquals("names"u8))
                {
                    Dictionary<string, string> dictionary = new Dictionary<string, string>();
                    foreach (var prop0 in prop.Value.EnumerateObject())
                    {
                        if ((prop0.Value.ValueKind == JsonValueKind.Null))
                        {
                            dictionary.Add(prop0.Name, null);
                        }
                        else
                        {
                            dictionary.Add(prop0.Name, prop0.Value.GetString());
                        }
                    }
                    names = dictionary;
                    continue;
                }
                if (prop.NameEquals("optionalNames"u8))
                {
                    if ((prop.Value.ValueKind == JsonValueKind.Null))
                    {
                        continue;
                    }
                    Dictionary<string, string> dictionary = new Dictionary<string, string>();
                    foreach (var prop0 in prop.Value.EnumerateObject())
                    {
                        if ((prop0.Value.ValueKind == JsonValueKind.Null))
                        {
                            dictionary.Add(prop0.Name, null);
                        }
                        else
                        {
                            dictionary.Add(prop0.Name, prop0.Value.GetString());
                        }
                    }
                    optionalNames = dictionary;
                    continue;
                }
                patch.Set([.. "$."u8, .. Encoding.UTF8.GetBytes(prop.Name)], prop.Value.GetUtf8Bytes());
            }
            return new global::Sample.Models.DynamicModel((cats ?? new ChangeTrackingDictionary<string, global::Sample.Models.Cat>()), names, (optionalNames ?? new ChangeTrackingDictionary<string, string>()), patch);
        }
    }
}
