// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using Sample.Models;

namespace Sample
{
    public partial class DynamicModel
    {
        internal static global::Sample.Models.DynamicModel DeserializeDynamicModel(JsonElement element, BinaryData data, ModelReaderWriterOptions options)
        {
            if ((element.ValueKind == JsonValueKind.Null))
            {
                return null;
            }
            global::Sample.Models.Cat cats = default;
            IDictionary<string, string> additionalProperties = new ChangeTrackingDictionary<string, string>();
#pragma warning disable SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
            JsonPatch patch = new JsonPatch((data is null) ? ReadOnlyMemory<byte>.Empty : data.ToMemory());
#pragma warning restore SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
            foreach (var prop in element.EnumerateObject())
            {
                if (prop.NameEquals("cats"u8))
                {
                    if ((prop.Value.ValueKind == JsonValueKind.Null))
                    {
                        continue;
                    }
                    cats = global::Sample.Models.Cat.DeserializeCat(prop.Value, options);
                    continue;
                }
                switch (prop.Value.ValueKind)
                {
                    case JsonValueKind.String:
                        additionalProperties.Add(prop.Name, prop.Value.GetString());
                        continue;
                }
                patch.Set([.. "$."u8, .. Encoding.UTF8.GetBytes(prop.Name)], prop.Value.GetUtf8Bytes());
            }
            return new global::Sample.Models.DynamicModel(cats, additionalProperties, patch);
        }
    }
}
