// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Text.Json;
using Sample.Models;

namespace Sample
{
    public partial class Cat
    {
        public static explicit operator Cat(ClientResult result)
        {
            PipelineResponse response = result.GetRawResponse();
            BinaryData data = response.Content;
            using JsonDocument document = JsonDocument.Parse(data, ModelSerializationExtensions.JsonDocumentOptions);
            return Cat.DeserializeCat(document.RootElement, data, ModelSerializationExtensions.WireOptions);
        }
    }
}
