// <auto-generated/>

#nullable disable

using System.ClientModel;
using System.ClientModel.Primitives;
using System.Text.Json;
using Sample.Models;

namespace Sample
{
    public partial class Cat
    {
        public static explicit operator Cat(ClientResult result)
        {
            PipelineResponse response = result.GetRawResponse();
            using JsonDocument document = JsonDocument.Parse(response.Content, ModelSerializationExtensions.JsonDocumentOptions);
            return global::Sample.Models.Cat.DeserializeCat(document.RootElement, ModelSerializationExtensions.WireOptions);
        }
    }
}
