// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Text;
using System.Text.Json;
using Sample.Models;

namespace Sample
{
    public partial class DynamicModel
    {
        BinaryData IPersistableModel<DynamicModel>.Write(ModelReaderWriterOptions options) => this.PersistableModelWriteCore(options);

        void IJsonModel<DynamicModel>.Write(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
#pragma warning disable SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
            if (Patch.Contains("$"u8))
            {
                writer.WriteRawValue(Patch.GetJson("$"u8));
                return;
            }
#pragma warning restore SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.

            writer.WriteStartObject();
            this.JsonModelWriteCore(writer, options);
            writer.WriteEndObject();
        }

        protected virtual void JsonModelWriteCore(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            string format = (options.Format == "W") ? ((IPersistableModel<DynamicModel>)this).GetFormatFromOptions(options) : options.Format;
            if ((format != "J"))
            {
                throw new FormatException($"The model {nameof(DynamicModel)} does not support writing '{format}' format.");
            }
#pragma warning disable SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
            if (Patch.Contains("$.propertyWithNestedArray"u8))
            {
                if (!Patch.IsRemoved("$.propertyWithNestedArray"u8))
                {
                    writer.WritePropertyName("propertyWithNestedArray"u8);
                    writer.WriteRawValue(Patch.GetJson("$.propertyWithNestedArray"u8));
                }
            }
            else if (Optional.IsCollectionDefined(PropertyWithNestedArray))
            {
                writer.WritePropertyName("propertyWithNestedArray"u8);
                writer.WriteStartArray();
                for (int i = 0; (i < PropertyWithNestedArray.Count); i++)
                {
                    if (Patch.IsRemoved(Encoding.UTF8.GetBytes($"$.propertyWithNestedArray[{i}]")))
                    {
                        continue;
                    }
                    if ((PropertyWithNestedArray[i] == null))
                    {
                        writer.WriteNullValue();
                        continue;
                    }
                    writer.WriteStartArray();
                    for (int i0 = 0; (i0 < PropertyWithNestedArray[i].Count); i0++)
                    {
                        if (Patch.IsRemoved(Encoding.UTF8.GetBytes($"$.propertyWithNestedArray[{i}][{i0}]")))
                        {
                            continue;
                        }
                        if ((PropertyWithNestedArray[i][i0] == null))
                        {
                            writer.WriteNullValue();
                            continue;
                        }
                        writer.WriteStartArray();
                        for (int i1 = 0; (i1 < PropertyWithNestedArray[i][i0].Count); i1++)
                        {
                            if (PropertyWithNestedArray[i][i0][i1].Patch.IsRemoved("$"u8))
                            {
                                continue;
                            }
                            writer.WriteObjectValue<DynamicCat>(PropertyWithNestedArray[i][i0][i1], options);
                        }
                        Patch.WriteTo(writer, Encoding.UTF8.GetBytes($"$.propertyWithNestedArray[{i}][{i0}]"));
                        writer.WriteEndArray();
                    }
                    Patch.WriteTo(writer, Encoding.UTF8.GetBytes($"$.propertyWithNestedArray[{i}]"));
                    writer.WriteEndArray();
                }
                Patch.WriteTo(writer, "$.propertyWithNestedArray"u8);
                writer.WriteEndArray();
            }

            Patch.WriteTo(writer);
#pragma warning restore SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
        }
    }
}
