// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Configuration;

namespace Sample
{
    public partial class TestClientOptions : ClientPipelineOptions
    {
        private const TestClientOptions.ServiceAServiceVersion LatestServiceAVersion = TestClientOptions.ServiceAServiceVersion.V2_0;
        private const TestClientOptions.ServiceBServiceVersion LatestServiceBVersion = TestClientOptions.ServiceBServiceVersion.V4_0;

        public TestClientOptions(TestClientOptions.ServiceAServiceVersion serviceAServiceVersion = LatestServiceAVersion, TestClientOptions.ServiceBServiceVersion serviceBServiceVersion = LatestServiceBVersion)
        {
            ServiceAApiVersion = serviceAServiceVersion switch
            {
                TestClientOptions.ServiceAServiceVersion.V1_0 => "1.0",
                TestClientOptions.ServiceAServiceVersion.V2_0 => "2.0",
                _ => throw new NotSupportedException()
            };
            ServiceBApiVersion = serviceBServiceVersion switch
            {
                TestClientOptions.ServiceBServiceVersion.V3_0 => "3.0",
                TestClientOptions.ServiceBServiceVersion.V4_0 => "4.0",
                _ => throw new NotSupportedException()
            };
        }

        [ExperimentalAttribute("SCME0002")]
        internal TestClientOptions(global::Microsoft.Extensions.Configuration.IConfigurationSection section) : base(section)
        {
            ServiceAApiVersion = "2.0";
            ServiceBApiVersion = "4.0";
            if (((section is null) || !section.Exists()))
            {
                return;
            }
            if ((section["ServiceAApiVersion"] is string serviceAApiVersion))
            {
                this.ServiceAApiVersion = serviceAApiVersion;
            }
            if ((section["ServiceBApiVersion"] is string serviceBApiVersion))
            {
                this.ServiceBApiVersion = serviceBApiVersion;
            }
        }

        internal string ServiceAApiVersion { get; }

        internal string ServiceBApiVersion { get; }

        public enum ServiceAServiceVersion
        {
            V1_0 = 1,
            V2_0 = 2
        }

        public enum ServiceBServiceVersion
        {
            V3_0 = 1,
            V4_0 = 2
        }
    }
}
