// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Configuration;

namespace Sample
{
    public partial class MultiServiceClientOptions : ClientPipelineOptions
    {
        private const MultiServiceClientOptions.ServiceOneServiceVersion LatestServiceOneVersion = MultiServiceClientOptions.ServiceOneServiceVersion.V2024_01_01;
        private const MultiServiceClientOptions.ServiceTwoServiceVersion LatestServiceTwoVersion = MultiServiceClientOptions.ServiceTwoServiceVersion.V2024_06_01;

        public MultiServiceClientOptions(MultiServiceClientOptions.ServiceOneServiceVersion serviceOneServiceVersion = LatestServiceOneVersion, MultiServiceClientOptions.ServiceTwoServiceVersion serviceTwoServiceVersion = LatestServiceTwoVersion)
        {
            ServiceOneApiVersion = serviceOneServiceVersion switch
            {
                MultiServiceClientOptions.ServiceOneServiceVersion.V2024_01_01 => "2024-01-01",
                _ => throw new NotSupportedException()
            };
            ServiceTwoApiVersion = serviceTwoServiceVersion switch
            {
                MultiServiceClientOptions.ServiceTwoServiceVersion.V2024_06_01 => "2024-06-01",
                _ => throw new NotSupportedException()
            };
        }

        [ExperimentalAttribute("SCME0002")]
        internal MultiServiceClientOptions(IConfigurationSection section) : base(section)
        {
            ServiceOneApiVersion = "2024-01-01";
            ServiceTwoApiVersion = "2024-06-01";
            if (((section is null) || !section.Exists()))
            {
                return;
            }
            if ((section["ServiceOneApiVersion"] is string serviceOneApiVersion))
            {
                this.ServiceOneApiVersion = serviceOneApiVersion;
            }
            if ((section["ServiceTwoApiVersion"] is string serviceTwoApiVersion))
            {
                this.ServiceTwoApiVersion = serviceTwoApiVersion;
            }
        }

        internal string ServiceOneApiVersion { get; }

        internal string ServiceTwoApiVersion { get; }

        public enum ServiceOneServiceVersion
        {
            V2024_01_01 = 1
        }

        public enum ServiceTwoServiceVersion
        {
            V2024_06_01 = 1
        }
    }
}
