// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Configuration;

namespace Sample
{
    public partial class TestClientOptions : ClientPipelineOptions
    {
        private const TestClientOptions.ServiceOneTestsVersion LatestServiceOneTestsVersion = TestClientOptions.ServiceOneTestsVersion.V2_0;
        private const TestClientOptions.ServiceTwoTestsVersion LatestServiceTwoTestsVersion = TestClientOptions.ServiceTwoTestsVersion.V4_0;

        public TestClientOptions(TestClientOptions.ServiceOneTestsVersion serviceOneTestsVersion = LatestServiceOneTestsVersion, TestClientOptions.ServiceTwoTestsVersion serviceTwoTestsVersion = LatestServiceTwoTestsVersion)
        {
            ServiceOneTestsApiVersion = serviceOneTestsVersion switch
            {
                TestClientOptions.ServiceOneTestsVersion.V1_0 => "1.0",
                TestClientOptions.ServiceOneTestsVersion.V2_0 => "2.0",
                _ => throw new NotSupportedException()
            };
            ServiceTwoTestsApiVersion = serviceTwoTestsVersion switch
            {
                TestClientOptions.ServiceTwoTestsVersion.V3_0 => "3.0",
                TestClientOptions.ServiceTwoTestsVersion.V4_0 => "4.0",
                _ => throw new NotSupportedException()
            };
        }

        [ExperimentalAttribute("SCME0002")]
        internal TestClientOptions(global::Microsoft.Extensions.Configuration.IConfigurationSection section) : base(section)
        {
            ServiceOneTestsApiVersion = "2.0";
            ServiceTwoTestsApiVersion = "4.0";
            if (((section is null) || !section.Exists()))
            {
                return;
            }
            if ((section["ServiceOneTestsApiVersion"] is string serviceOneTestsApiVersion))
            {
                this.ServiceOneTestsApiVersion = serviceOneTestsApiVersion;
            }
            if ((section["ServiceTwoTestsApiVersion"] is string serviceTwoTestsApiVersion))
            {
                this.ServiceTwoTestsApiVersion = serviceTwoTestsApiVersion;
            }
        }

        internal string ServiceOneTestsApiVersion { get; }

        internal string ServiceTwoTestsApiVersion { get; }

        public enum ServiceOneTestsVersion
        {
            V1_0 = 1,
            V2_0 = 2
        }

        public enum ServiceTwoTestsVersion
        {
            V3_0 = 1,
            V4_0 = 2
        }
    }
}
