// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Configuration;

namespace Sample
{
    public partial class MultiServiceClientOptions : ClientPipelineOptions
    {
        private const MultiServiceClientOptions.AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsVersion LatestAzureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsVersion = MultiServiceClientOptions.AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsVersion.V2024_01_01;
        private const MultiServiceClientOptions.AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsVersion LatestAzureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsVersion = MultiServiceClientOptions.AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsVersion.V2024_06_01;

        public MultiServiceClientOptions(MultiServiceClientOptions.AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsVersion azureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsVersion = LatestAzureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsVersion, MultiServiceClientOptions.AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsVersion azureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsVersion = LatestAzureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsVersion)
        {
            AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsApiVersion = azureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsVersion switch
            {
                MultiServiceClientOptions.AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsVersion.V2024_01_01 => "2024-01-01",
                _ => throw new NotSupportedException()
            };
            AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsApiVersion = azureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsVersion switch
            {
                MultiServiceClientOptions.AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsVersion.V2024_06_01 => "2024-06-01",
                _ => throw new NotSupportedException()
            };
        }

        [ExperimentalAttribute("SCME0002")]
        internal MultiServiceClientOptions(global::Microsoft.Extensions.Configuration.IConfigurationSection section) : base(section)
        {
            AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsApiVersion = "2024-01-01";
            AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsApiVersion = "2024-06-01";
            if (((section is null) || !section.Exists()))
            {
                return;
            }
            if ((section["AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsApiVersion"] is string azureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsApiVersion))
            {
                this.AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsApiVersion = azureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsApiVersion;
            }
            if ((section["AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsApiVersion"] is string azureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsApiVersion))
            {
                this.AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsApiVersion = azureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsApiVersion;
            }
        }

        internal string AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsApiVersion { get; }

        internal string AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsApiVersion { get; }

        public enum AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceOneVersionsVersion
        {
            V2024_01_01 = 1
        }

        public enum AzureGeneratorMgmtTypeSpecMultiServiceTestsServiceTwoVersionsVersion
        {
            V2024_06_01 = 1
        }
    }
}
