// <auto-generated/>

#nullable disable

using System;

namespace Sample
{
    [ObsoleteAttribute]
    [ObsoleteAttribute("This is obsolete")]
    [ObsoleteAttribute("This is obsolete", true)]
    [ObsoleteAttribute(DiagnosticId = "TypeSpecGenerator001")]
    [ObsoleteAttribute(DiagnosticId = "TypeSpecGenerator001", UrlFormat = "my-format")]
    [ObsoleteAttribute("This is obsolete", true, DiagnosticId = "TypeSpecGenerator001", UrlFormat = "my-format")]
    public partial class ProviderWithAttributes
    {
    }
}
