// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Threading;
using Sample.Compute;
using Sample.KeyVault;
using Sample.Storage;

namespace Sample
{
    public partial class TestClient
    {
        private readonly Uri _endpoint;
        private readonly string _subscriptionId;
        private readonly string _computeApiVersion;
        private readonly string _keyVaultApiVersion;
        private readonly string _storageApiVersion;
        private global::Sample.KeyVault.KeyVault _cachedKeyVault;
        private global::Sample.Storage.Storage _cachedStorage;
        private global::Sample.Compute.Compute _cachedCompute;

        protected TestClient()
        {
        }

        public TestClient(Uri endpoint, string subscriptionId) : this(endpoint, subscriptionId, new TestClientOptions())
        {
        }

        internal TestClient(AuthenticationPolicy authenticationPolicy, Uri endpoint, string subscriptionId, TestClientOptions options)
        {
            Argument.AssertNotNull(endpoint, nameof(endpoint));
            Argument.AssertNotNullOrEmpty(subscriptionId, nameof(subscriptionId));

            options ??= new TestClientOptions();

            _endpoint = endpoint;
            _subscriptionId = subscriptionId;
            if ((authenticationPolicy != null))
            {
                Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(TestClient).Assembly), authenticationPolicy }, Array.Empty<PipelinePolicy>());
            }
            else
            {
                Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(TestClient).Assembly) }, Array.Empty<PipelinePolicy>());
            }
            _computeApiVersion = options.ComputeApiVersion;
            _keyVaultApiVersion = options.KeyVaultApiVersion;
            _storageApiVersion = options.StorageApiVersion;
        }

        public TestClient(Uri endpoint, string subscriptionId, TestClientOptions options) : this(null, endpoint, subscriptionId, options)
        {
        }

        public ClientPipeline Pipeline { get; }

        public virtual global::Sample.KeyVault.KeyVault GetKeyVaultClient()
        {
            return (Volatile.Read(ref _cachedKeyVault) ?? (Interlocked.CompareExchange(ref _cachedKeyVault, new global::Sample.KeyVault.KeyVault(Pipeline, _endpoint, _keyVaultApiVersion, _subscriptionId), null) ?? _cachedKeyVault));
        }

        public virtual global::Sample.Storage.Storage GetStorageClient()
        {
            return (Volatile.Read(ref _cachedStorage) ?? (Interlocked.CompareExchange(ref _cachedStorage, new global::Sample.Storage.Storage(Pipeline, _endpoint, _storageApiVersion, _subscriptionId), null) ?? _cachedStorage));
        }

        public virtual global::Sample.Compute.Compute GetComputeClient()
        {
            return (Volatile.Read(ref _cachedCompute) ?? (Interlocked.CompareExchange(ref _cachedCompute, new global::Sample.Compute.Compute(Pipeline, _endpoint, _computeApiVersion, _subscriptionId), null) ?? _cachedCompute));
        }
    }
}
