// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Threading;
using Sample.ServiceA;
using Sample.ServiceB;

namespace Sample
{
    public partial class TestClient
    {
        private readonly Uri _endpoint;
        private readonly string _subscriptionId;
        private readonly string _serviceAApiVersion;
        private readonly string _serviceBApiVersion;
        private Sample.ServiceA.ServiceA _cachedServiceA;
        private Sample.ServiceB.ServiceB _cachedServiceB;

        protected TestClient()
        {
        }

        public TestClient(Uri endpoint, string subscriptionId) : this(endpoint, subscriptionId, new TestClientOptions())
        {
        }

        internal TestClient(AuthenticationPolicy authenticationPolicy, Uri endpoint, string subscriptionId, TestClientOptions options)
        {
            Argument.AssertNotNull(endpoint, nameof(endpoint));
            Argument.AssertNotNullOrEmpty(subscriptionId, nameof(subscriptionId));

            options ??= new TestClientOptions();

            _endpoint = endpoint;
            _subscriptionId = subscriptionId;
            if ((authenticationPolicy != null))
            {
                Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(TestClient).Assembly), authenticationPolicy }, Array.Empty<PipelinePolicy>());
            }
            else
            {
                Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(TestClient).Assembly) }, Array.Empty<PipelinePolicy>());
            }
            _serviceAApiVersion = options.ServiceAApiVersion;
            _serviceBApiVersion = options.ServiceBApiVersion;
        }

        public TestClient(Uri endpoint, string subscriptionId, TestClientOptions options) : this(null, endpoint, subscriptionId, options)
        {
        }

        public ClientPipeline Pipeline { get; }

        public virtual Sample.ServiceA.ServiceA GetServiceAClient()
        {
            return (Volatile.Read(ref _cachedServiceA) ?? (Interlocked.CompareExchange(ref _cachedServiceA, new Sample.ServiceA.ServiceA(Pipeline, _endpoint, _serviceAApiVersion, _subscriptionId), null) ?? _cachedServiceA));
        }

        public virtual Sample.ServiceB.ServiceB GetServiceBClient()
        {
            return (Volatile.Read(ref _cachedServiceB) ?? (Interlocked.CompareExchange(ref _cachedServiceB, new Sample.ServiceB.ServiceB(Pipeline, _endpoint, _serviceBApiVersion, _subscriptionId), null) ?? _cachedServiceB));
        }
    }
}
