// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Threading;
using System.Threading.Tasks;

namespace Sample
{
    public partial class TestClient
    {
        private readonly Uri _endpoint;
        private readonly string _computeApiVersion;
        private readonly string _keyVaultApiVersion;
        private readonly string _storageApiVersion;

        protected TestClient()
        {
        }

        public TestClient(Uri endpoint) : this(endpoint, new TestClientOptions())
        {
        }

        internal TestClient(AuthenticationPolicy authenticationPolicy, Uri endpoint, TestClientOptions options)
        {
            Argument.AssertNotNull(endpoint, nameof(endpoint));

            options ??= new TestClientOptions();

            _endpoint = endpoint;
            if ((authenticationPolicy != null))
            {
                Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(TestClient).Assembly), authenticationPolicy }, Array.Empty<PipelinePolicy>());
            }
            else
            {
                Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(TestClient).Assembly) }, Array.Empty<PipelinePolicy>());
            }
            _computeApiVersion = options.ComputeApiVersion;
            _keyVaultApiVersion = options.KeyVaultApiVersion;
            _storageApiVersion = options.StorageApiVersion;
        }

        public TestClient(Uri endpoint, TestClientOptions options) : this(null, endpoint, options)
        {
        }

        public ClientPipeline Pipeline { get; }

        public virtual ClientResult KeyVaultOperation(RequestOptions options)
        {
            using PipelineMessage message = this.CreateKeyVaultOperationRequest(options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        public virtual async Task<ClientResult> KeyVaultOperationAsync(RequestOptions options)
        {
            using PipelineMessage message = this.CreateKeyVaultOperationRequest(options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        public virtual ClientResult KeyVaultOperation(CancellationToken cancellationToken = default)
        {
            return this.KeyVaultOperation(cancellationToken.ToRequestOptions());
        }

        public virtual async Task<ClientResult> KeyVaultOperationAsync(CancellationToken cancellationToken = default)
        {
            return await this.KeyVaultOperationAsync(cancellationToken.ToRequestOptions()).ConfigureAwait(false);
        }

        public virtual ClientResult StorageOperation(RequestOptions options)
        {
            using PipelineMessage message = this.CreateStorageOperationRequest(options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        public virtual async Task<ClientResult> StorageOperationAsync(RequestOptions options)
        {
            using PipelineMessage message = this.CreateStorageOperationRequest(options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        public virtual ClientResult StorageOperation(CancellationToken cancellationToken = default)
        {
            return this.StorageOperation(cancellationToken.ToRequestOptions());
        }

        public virtual async Task<ClientResult> StorageOperationAsync(CancellationToken cancellationToken = default)
        {
            return await this.StorageOperationAsync(cancellationToken.ToRequestOptions()).ConfigureAwait(false);
        }

        public virtual ClientResult ComputeOperation(RequestOptions options)
        {
            using PipelineMessage message = this.CreateComputeOperationRequest(options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        public virtual async Task<ClientResult> ComputeOperationAsync(RequestOptions options)
        {
            using PipelineMessage message = this.CreateComputeOperationRequest(options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        public virtual ClientResult ComputeOperation(CancellationToken cancellationToken = default)
        {
            return this.ComputeOperation(cancellationToken.ToRequestOptions());
        }

        public virtual async Task<ClientResult> ComputeOperationAsync(CancellationToken cancellationToken = default)
        {
            return await this.ComputeOperationAsync(cancellationToken.ToRequestOptions()).ConfigureAwait(false);
        }
    }
}
