// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Threading;
using System.Threading.Tasks;

namespace Sample
{
    public partial class TestClient
    {
        private readonly Uri _endpoint;
        private readonly string _serviceAApiVersion;
        private readonly string _serviceBApiVersion;

        protected TestClient()
        {
        }

        public TestClient(Uri endpoint) : this(endpoint, new TestClientOptions())
        {
        }

        internal TestClient(AuthenticationPolicy authenticationPolicy, Uri endpoint, TestClientOptions options)
        {
            Argument.AssertNotNull(endpoint, nameof(endpoint));

            options ??= new TestClientOptions();

            _endpoint = endpoint;
            if ((authenticationPolicy != null))
            {
                Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(TestClient).Assembly), authenticationPolicy }, Array.Empty<PipelinePolicy>());
            }
            else
            {
                Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(TestClient).Assembly) }, Array.Empty<PipelinePolicy>());
            }
            _serviceAApiVersion = options.ServiceAApiVersion;
            _serviceBApiVersion = options.ServiceBApiVersion;
        }

        public TestClient(Uri endpoint, TestClientOptions options) : this(null, endpoint, options)
        {
        }

        public ClientPipeline Pipeline { get; }

        public virtual ClientResult ServiceAOperation(RequestOptions options)
        {
            using PipelineMessage message = this.CreateServiceAOperationRequest(options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        public virtual async Task<ClientResult> ServiceAOperationAsync(RequestOptions options)
        {
            using PipelineMessage message = this.CreateServiceAOperationRequest(options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        public virtual ClientResult ServiceAOperation(CancellationToken cancellationToken = default)
        {
            return this.ServiceAOperation(cancellationToken.ToRequestOptions());
        }

        public virtual async Task<ClientResult> ServiceAOperationAsync(CancellationToken cancellationToken = default)
        {
            return await this.ServiceAOperationAsync(cancellationToken.ToRequestOptions()).ConfigureAwait(false);
        }

        public virtual ClientResult ServiceBOperation(RequestOptions options)
        {
            using PipelineMessage message = this.CreateServiceBOperationRequest(options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        public virtual async Task<ClientResult> ServiceBOperationAsync(RequestOptions options)
        {
            using PipelineMessage message = this.CreateServiceBOperationRequest(options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        public virtual ClientResult ServiceBOperation(CancellationToken cancellationToken = default)
        {
            return this.ServiceBOperation(cancellationToken.ToRequestOptions());
        }

        public virtual async Task<ClientResult> ServiceBOperationAsync(CancellationToken cancellationToken = default)
        {
            return await this.ServiceBOperationAsync(cancellationToken.ToRequestOptions()).ConfigureAwait(false);
        }
    }
}
