// <auto-generated/>

#nullable disable

using System.ClientModel;
using System.Threading;
using System.Threading.Tasks;
using Sample.Models;

namespace Sample
{
    public partial class TestClient
    {
        public virtual async Task<ClientResult> TestOperationAsync(ModelWithPathParam body, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNull(body, nameof(body));

            return await this.TestOperationAsync(body.Foo, body, cancellationToken.ToRequestOptions()).ConfigureAwait(false);
        }
    }
}
