// <auto-generated/>

#nullable disable

using System.ClientModel;
using System.Threading;
using Sample.Models;

namespace Sample
{
    public partial class TestClient
    {
        public virtual ClientResult Operation(InputEnum queryParam, CancellationToken cancellationToken = default)
        {
            return this.Operation(queryParam.ToString(), cancellationToken.ToRequestOptions());
        }
    }
}
