// <auto-generated/>

#nullable disable

using System.ClientModel;
using System.Threading;
using System.Threading.Tasks;
using Sample.Models;

namespace Sample
{
    public partial class TestClient
    {
        public virtual async Task<ClientResult> OperationAsync(global::Sample.Models.InputEnum queryParam, CancellationToken cancellationToken = default)
        {
            return await this.OperationAsync(queryParam.ToString(), cancellationToken.ToRequestOptions()).ConfigureAwait(false);
        }
    }
}
