// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Sample;

namespace Sample.Models
{
    public partial class DerivedModel : BaseModel
    {
        public DerivedModel(string baseProp, int derivedProp) : base(baseProp)
        {
            Argument.AssertNotNull(baseProp, nameof(baseProp));

            DerivedProp = derivedProp;
            Kind = KindEnum.One;
        }

        internal DerivedModel(KindEnum? kind, string baseProp, IDictionary<string, BinaryData> additionalBinaryDataProperties, int derivedProp) : base(kind, baseProp, additionalBinaryDataProperties)
        {
            DerivedProp = derivedProp;
        }

        public int DerivedProp { get; set; }
    }
}
